export const GET_EMPLOYEE_LIST = "GET_EMPLOYEE_LIST";
export const SHOW_SUCCESS_TOAST = "SHOW_SUCCESS_TOAST";
export const HIDE_SUCCESS_TOAST = "HIDE_SUCCESS_TOAST";
export const SHOW_ERROR_TOAST = "SHOW_ERROR_TOAST";
export const HIDE_ERROR_TOAST = "HIDE_ERROR_TOAST";
export const GET_EMPLOYEE_BY_ID = "GET_EMPLOYEE_BY_ID";
export const SET_FORM_MODE = "SET_FORM_MODE";
//export const
